/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/8Bs6zPjCXdl
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Caudex } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

caudex({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import Image from 'next/image'
import { Button } from "@/components/ui/button"
import { CollapsibleTrigger, CollapsibleContent, Collapsible } from "@/components/ui/collapsible"
import { ShiftTextImageSection } from '../components/ui/shift-text-side-image-section'
import { Footer } from '../components/footer'
import { SupportDialog } from '../components/ui/support-dialog'
import { ChevronDownIcon, WhatsAppIcon, ArrowRightIcon } from '../components/icons'

const homeContent = [
  { 
    textPosition: 'left',
    headText: 'Conversação Natural',
    bodyText: 'Converse por áudio e texto com Olivia, nossa IA que ajuda a tornar suas conversas fluidas e engajadoras. Ela ajusta a complexidade ao seu nível e fornece correções sutis de gramática e pronúncia ao longo do papo, sem julgamento.',
    imageURL: '/assets/images/everylang_conversation.png'
  },
  { 
    textPosition: 'right',
    headText: 'Exercícios de Pronúncia',
    bodyText: 'Receba feedback instantâneo e realize exercícios personalizados para corrigir suas dificuldades. A Olivia identifica padrões e cria atividades direcionadas para aperfeiçoar sua pronúncia de maneira eficaz.',
    imageURL: '/assets/images/everylang_pronunciation.png'
  },
  { 
    textPosition: 'left',
    headText: 'Exercícios de Gramática',
    bodyText: 'Corrija erros gramaticais comuns com orientações em tempo real. Os exercícios personalizados ajudam a desenvolver sua gramática de forma prática e adaptada às suas necessidades.',
    imageURL: '/assets/images/everylang_grammar.png'
  },
  { 
    textPosition: 'right',
    headText: 'Simulados Práticos',
    bodyText: 'Treine situações reais, como pedir em um restaurante ou fazer check-in em um hotel, para ganhar confiança e fluência. Ao final de cada simulado, você recebe feedback detalhado.',
    imageURL: '/assets/images/everylang_simulation.png'
  },
]

const faq = [
  {
    // id: uuidv4(),
    heading: `O que é o Everylang?`,
    detail: 'O Everylang é uma IA que permite que você pratique um idioma pelo WhatsApp. Conversando com Olivia, sua professora virtual, você pode ter conversas reais e personalizadas, além de exercícios de pronúncia e gramática adaptados às suas necessidades.',
  },
  {
    // id: uuidv4(),
    heading: `Como utilizar?`,
    detail: 'É tão simples quanto enviar uma mensagem no WhatsApp. Abra a conta do Everylang, envie uma mensagem para Olivia, e inicie uma conversa ou faça exercícios facilmente.',
  },
  {
    // id: uuidv4(),
    heading: `É grátis?`,
    detail: 'Você pode testar gratuitamente. Se gostar, continue utilizando o serviço com um plano mensal ou anual.',
  },
  {
    // id: uuidv4(),
    heading: `Quais idiomas posso estudar?`,
    detail: 'Você pode praticar conversação, pronúncia e gramática em inglês, espanhol, francês, alemão, coreano, mandarim e japonês.',
  },
  {
    // id: uuidv4(),
    heading: `Serve para o meu nível?`,
    detail: 'O Everylang adapta-se ao seu nível, desde iniciantes até avançados. Pratique sem medo ou julgamento.',
  },
  {
    // id: uuidv4(),
    heading: `Já estudo um idioma com um professor ou escola, posso usar o Everylang?`,
    detail: 'Claro! Mostre o Everylang ao seu professor para que ele possa criar exercícios personalizados, potencializando ainda mais suas aulas.',
  }
]

export default function LandingPageHome() {
  return (
    <>
      <header className="fixed top-0 left-0 right-0 z-50 flex h-16 w-full items-center justify-between bg-white px-6 shadow-sm dark:bg-gray-950">
        <Link className="flex items-center gap-2" href="#">
        <Image
              priority
              src="/assets/logo/everylang_logo_transparent_square_fit.png" 
              alt="Everylang logo" 
              width={42} 
              height={42} 
            />
          <span className="text-lg font-bold text-darkColor">Everylang</span>
        </Link>

        <Link
                className="bg-mainColor text-white inline-flex items-center rounded-md bg-gray-900 px-4 py-2 text-sm font-medium shadow transition-colors hover:bg-darkColor focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-darkColor dark:focus-visible:ring-gray-300"
                href="/school"
              >
              Sou professor
              <ArrowRightIcon className="ml-2 h-4 w-4" />
            </Link>
      </header>
      <main>
        <section className="relative h-[80vh] w-full bg-gradient-to-br from-darkColor to-mainColor pt-20">
          <div className="container mx-auto flex h-full flex-col items-center justify-center gap-2 px-4 text-center">
            <Image
              priority
              src="/assets/logo/everylang_logo_transparent_square_fit.png" 
              alt="Everylang logo" 
              width={62} 
              height={62} 
            />
            <h1 className="text-4xl font-bold text-white md:text-5xl lg:text-6xl">Everylang</h1>
            <p className="mt-4 mb-8 max-w-md text-lg text-white">
            Estude pronúncia e gramática com conversação e exercícios via WhatsApp
            </p>
            <p className="max-w-md text-lg text-white">
            Teste grátis
            </p>
            <Button
                className="bg-white text-[#6c5ce7] hover:bg-gray-200"
                size="lg"
              >
                <WhatsAppIcon className="mr-2 h-6 w-6" />
                Começar agora
              </Button>
          </div>
        </section>

        <section className="w-full">
          <div className="container mx-auto h-full gap-4 px-4">

        {
          homeContent.map((item) => (<ShiftTextImageSection key={item.headText} headText={item.headText} bodyText={item.bodyText} imageSRC={item.imageURL} textSide={item.textPosition} />))
        }
          </div>
         </section> 
        <section className="container mx-auto py-16">
          <h2 className="mb-8 text-center text-3xl font-bold text-[#6c5ce7]">Perguntas frequêntes</h2>
          <div className="grid gap-4">

          {faq.map((accordion) => (
             <Collapsible key={accordion.heading}>
             <CollapsibleTrigger className="flex w-full items-center justify-between rounded-md bg-gray-100 px-4 py-3 text-lg font-medium text-gray-800 transition-colors hover:bg-gray-200 dark:bg-gray-800 dark:text-gray-200 dark:hover:bg-gray-700">
             {accordion.heading}
               <ChevronDownIcon className="h-5 w-5 transition-transform" />
             </CollapsibleTrigger>
             <CollapsibleContent className="rounded-md bg-gray-100 px-4 py-3 text-gray-600 dark:bg-gray-800 dark:text-gray-400">
             {accordion.detail}
             </CollapsibleContent>
           </Collapsible>
      ))}
          </div>
        </section>
        {/* <section className="container mx-auto grid grid-cols-1 gap-12 py-16 md:grid-cols-2">
          <div className="flex flex-col items-start justify-center gap-4">
            <h2 className="text-3xl font-bold text-[#6c5ce7]">What Our Users Say</h2>
            <p className="text-lg text-gray-600 dark:text-gray-400">
              Hear from our satisfied customers and see how our app has helped them boost their productivity.
            </p>
          </div>
          <div className="grid gap-4">
            <Card className="flex flex-col items-start gap-4 rounded-md bg-gray-100 p-4 dark:bg-gray-800">
              <div className="flex items-center gap-4">
                <div className="h-12 w-12 rounded-full bg-[#6c5ce7] text-2xl font-bold text-white flex items-center justify-center">
                  JD
                </div>
                <div>
                  <h3 className="text-lg font-bold">John Doe</h3>
                  <p className="text-gray-600 dark:text-gray-400">Acme User</p>
                </div>
              </div>
              <p className="text-gray-600 dark:text-gray-400">
                "I've been using the Acme app for a few months now and it's completely transformed the way I work. The
                task management and collaboration features are so helpful, and the app is just a joy to use."
              </p>
            </Card>
            <Card className="flex flex-col items-start gap-4 rounded-md bg-gray-100 p-4 dark:bg-gray-800">
              <div className="flex items-center gap-4">
                <div className="h-12 w-12 rounded-full bg-[#6c5ce7] text-2xl font-bold text-white flex items-center justify-center">
                  JD
                </div>
                <div>
                  <h3 className="text-lg font-bold">Jane Doe</h3>
                  <p className="text-gray-600 dark:text-gray-400">Acme User</p>
                </div>
              </div>
              <p className="text-gray-600 dark:text-gray-400">
                "I've been using the Acme app for a few months now and it's completely transformed the way I work. The
                task management and collaboration features are so helpful, and the app is just a joy to use."
              </p>
            </Card>
          </div>
        </section> */}
        <section className="relative h-[80vh] w-full bg-gradient-to-br from-mainColor to-darkColor pt-20">
          <div className="container mx-auto flex h-full flex-col items-center justify-center gap-8 px-4 text-center">
            <h1 className="text-4xl font-bold text-white md:text-5xl lg:text-6xl">
              Você é professor ou escola?
            </h1>
            <p className="max-w-md text-lg text-white">
            Utilize a tecnologia Everylang com seus alunos.
            </p>
          

              <Link
                className="bg-white text-[#6c5ce7] inline-flex items-center rounded-md bg-gray-900 px-4 py-2 text-sm font-medium shadow transition-colors hover:bg-gray-200 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-200 dark:focus-visible:ring-gray-300"
                href="/school"
              >
              Confira os benefícios
              <ArrowRightIcon className="ml-2 h-4 w-4" />
            </Link>
          </div>
        </section>
      </main>
      <Footer />
      <SupportDialog />
    </>
  )
}
