/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/8Bs6zPjCXdl
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Caudex } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

caudex({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import Image from 'next/image'
import Head from 'next/head';
import { CollapsibleTrigger, CollapsibleContent, Collapsible } from "@/components/ui/collapsible"
import { ShiftTextImageSection } from '../components/ui/shift-text-side-image-section'
import { Footer } from '@/components/footer'
import { SupportDialog } from '../components/ui/support-dialog'
import { ArrowRightIcon, GiftIcon, ChevronDownIcon } from '../components/icons'

const homeContent = [
  { 
    textPosition: 'left',
    headText: 'Crie Exercícios de Pronúncia Personalizados',
    bodyText: 'Explicar a pronúncia correta em sala de aula não garante que o aluno consiga praticar posteriormente. Com a Everylang, você cria exercícios de pronúncia personalizados com base nas palavras que o aluno tem mais dificuldade. Ao receber os exercícios, o aluno poderá praticar em seu rítmo após as aulas. Tanto o aluno quanto o professor, recebem um feedback detalhado da pronúncia.',
    imageURL: '/assets/images/everylang_school_pronunciation.png'
  },
  { 
    textPosition: 'right',
    headText: 'Crie Exercícios de Gramática Personalizados',
    bodyText: 'Edutar gramática pode ser uma tarefa desafiadora para boa parte dos alunos. Com a Everylang, essa tarefa é incorporado em algo que ele já faz todos os dias, conversar no WhatsApp. Assim, ele irá realizar exercícios personalizados para a suas próprias dificuldades, recebendo feedback a cada exercício.',
    imageURL: '/assets/images/everylang_school_grammar.png'
  },
  { 
    textPosition: 'left',
    headText: 'Desempenho dos alunos',
    bodyText: 'Através de uma dashboard completa, você consegue acompanhar as atividades e o engajamento dos alunos. Confira atividades diárias, totais de atividades, lições em andamento e outras informações que com relatório do desempenho geral ou individual dos alunos.',
    imageURL: '/assets/images/everylang_students_performance.png'
  },
  { 
    textPosition: 'right',
    headText: 'Insights valiosos para planejar a sua aula',
    bodyText: 'O Everylang fornece dados detalhados sobre o desempenho e as necessidades específicas de cada aluno. Você pode acompanhar suas áreas de dificuldade em gramática e pronúncia, permitindo identificar padrões de aprendizado e pontos que precisam de reforço. A IA também ajuda a criar exercícios personalizados, adaptados ao nível de cada aluno, tornando seu planejamento mais estratégico e alinhado ao progresso dos estudantes.',
    imageURL: '/assets/images/everylang_insight.png'
  },
]

const faq = [
  {
    // id: uuidv4(),
    heading: `O que é o Everylang para professores?`,
    detail: 'O Everylang disponibiliza ferramentas com inteligência artificial para que o professor possa criar exercícios de pronúncia e gramática e permitir que seus alunos estudem fazendo o que eles já fazem todos os dias: usar o WhatsApp. Assim, incorporando o estudo em uma rotina que o aluno já tem.',
  },
  {
    // id: uuidv4(),
    heading: `É grátis?`,
    detail: 'Sim, o Everylang é gratuito para professores e escolas. No entanto, os alunos precisam ter uma assinatura para utilizar os serviços oferecidos pela plataforma.Você pode testar gratuitamente. Se gostar, continue utilizando o serviço com um plano mensal ou anual.',
  },
  {
    // id: uuidv4(),
    heading: `Como posso acompanhar o desempenho dos meus alunos no Everylang?`,
    detail: 'O Everylang oferece uma dashboard completa onde os professores podem acompanhar as atividades e o engajamento dos alunos. É possível ver atividades diárias, totais de atividades, lições em andamento e outras informações detalhadas sobre o desempenho geral ou individual dos alunos.',
  },
  {
    // id: uuidv4(),
    heading: `Os exercícios de pronúncia incluem feedback com gravações de áudio?`,
    detail: 'Sim! Para cada exercícios respondido, o professor recebe todas as tentativas do aluno, incluindo a tentativa que o Everylang aprovou. O professor também recebe todas as notas de cada palavras que o aluno pronúnciou.',
  }
]

export default function LandingPageSchool() {
  return (
    <>
      <Head>
        <title>Crie exercícios de pronúncia e gramática para seus alunos | Everylang</title>
        <meta name="description" content="Crie exercícios de pronúncia e gramática para seus alunos." />
        <link href="https://lp.everylang.ai" rel="canonical" />

        <meta property="og:title" content="Crie exercícios de pronúncia e gramática para seus alunos" />
        <meta property="og:url" content="https://lp.everylang.ai" />
        <meta property="og:description" content="Crie exercícios de pronúncia e gramática para seus alunos" />
        <meta property="og:image" content="https://www.everylang.ai/assets/everylang_logo_purple_square.png" />
      </Head>
      <header className="fixed top-0 left-0 right-0 z-50 flex h-16 w-full items-center justify-between bg-white px-6 shadow-sm dark:bg-gray-950">
        <Link className="flex items-center gap-2" href="/">
        <Image
              priority
              src="/assets/logo/everylang_logo_transparent_square_fit.png" 
              alt="Everylang logo" 
              width={42} 
              height={42} 
            />
          <span className="text-lg font-bold text-darkColor">Everylang</span>
        </Link>
      </header>
      <main>
        <section className="relative h-[100vh] w-full bg-gradient-to-br from-darkColor to-mainColor pt-20">
          <div className="container mx-auto flex h-full flex-col items-center justify-center gap-2 px-2 text-center">
            <Image
              priority
              src="/assets/logo/everylang_logo_transparent_square_fit.png" 
              alt="Everylang logo" 
              width={62} 
              height={62} 
            />
            <h1 className="text-4xl font-bold text-white md:text-5xl lg:text-6xl">Everylang</h1>
            <h3 className="text-lg font-bold text-white">Para professores</h3>
            <p className="mt-4 max-w-md text-lg text-white">
            Uma forma eficiênte de seus alunos estudarem pronúncia e gramática após as aulas.
            </p>
            {/* <p className="max-w-md text-lg text-white">
            Confira
            </p> */}
              <div className="mb-4 flex items-center justify-center aspect-video w-full rounded-lg" >
                <iframe width="560" height="315" src="https://www.youtube.com/embed/gJnMl3QwIfM?si=W3hI1MXBGgsJiU6V" title="YouTube video player" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" />
              </div>
          </div>
         
        </section>
        <section className="bg-[#6c5ce7] py-12 text-white">
          <div className="container mx-auto px-4">
            <div className="flex items-center justify-center">
              <GiftIcon className="mr-2 h-6 w-6" />
              <h2 className="text-2xl font-bold">100% grátis para professores</h2>
            </div>
          </div>
        </section>
        <section className="w-full">
          <div className="container mx-auto h-full gap-4 px-4">

        {
          homeContent.map((item) => (<ShiftTextImageSection key={item.headText} headText={item.headText} bodyText={item.bodyText} imageSRC={item.imageURL} imageWidth={500} imageHight={500} textSide={item.textPosition} />))
        }
          </div>

        </section>
        <section className="container mx-auto py-16">
          <h2 className="mb-8 text-center text-3xl font-bold text-[#6c5ce7]">Perguntas frequêntes</h2>
          <div className="grid gap-4">

          {faq.map((accordion) => (
             <Collapsible key={accordion.heading}>
             <CollapsibleTrigger className="flex w-full items-center justify-between rounded-md bg-gray-100 px-4 py-3 text-lg font-medium text-gray-800 transition-colors hover:bg-gray-200 dark:bg-gray-800 dark:text-gray-200 dark:hover:bg-gray-700">
             {accordion.heading}
               <ChevronDownIcon className="h-5 w-5 transition-transform" />
             </CollapsibleTrigger>
             <CollapsibleContent className="rounded-md bg-gray-100 px-4 py-3 text-gray-600 dark:bg-gray-800 dark:text-gray-400">
             {accordion.detail}
             </CollapsibleContent>
           </Collapsible>
      ))}
          </div>
        </section>
        {/* <section className="container mx-auto grid grid-cols-1 gap-12 py-16 md:grid-cols-2">
          <div className="flex flex-col items-start justify-center gap-4">
            <h2 className="text-3xl font-bold text-[#6c5ce7]">What Our Users Say</h2>
            <p className="text-lg text-gray-600 dark:text-gray-400">
              Hear from our satisfied customers and see how our app has helped them boost their productivity.
            </p>
          </div>
          <div className="grid gap-4">
            <Card className="flex flex-col items-start gap-4 rounded-md bg-gray-100 p-4 dark:bg-gray-800">
              <div className="flex items-center gap-4">
                <div className="h-12 w-12 rounded-full bg-[#6c5ce7] text-2xl font-bold text-white flex items-center justify-center">
                  JD
                </div>
                <div>
                  <h3 className="text-lg font-bold">John Doe</h3>
                  <p className="text-gray-600 dark:text-gray-400">Acme User</p>
                </div>
              </div>
              <p className="text-gray-600 dark:text-gray-400">
                "I've been using the Acme app for a few months now and it's completely transformed the way I work. The
                task management and collaboration features are so helpful, and the app is just a joy to use."
              </p>
            </Card>
            <Card className="flex flex-col items-start gap-4 rounded-md bg-gray-100 p-4 dark:bg-gray-800">
              <div className="flex items-center gap-4">
                <div className="h-12 w-12 rounded-full bg-[#6c5ce7] text-2xl font-bold text-white flex items-center justify-center">
                  JD
                </div>
                <div>
                  <h3 className="text-lg font-bold">Jane Doe</h3>
                  <p className="text-gray-600 dark:text-gray-400">Acme User</p>
                </div>
              </div>
              <p className="text-gray-600 dark:text-gray-400">
                "I've been using the Acme app for a few months now and it's completely transformed the way I work. The
                task management and collaboration features are so helpful, and the app is just a joy to use."
              </p>
            </Card>
          </div>
        </section> */}
        <section className="relative h-[50vh] w-full bg-gradient-to-br from-mainColor to-darkColor">
          <div className="container mx-auto flex h-full flex-col items-center justify-center gap-4 px-1 text-center">
            <h1 className="text-4xl font-bold text-white md:text-5xl lg:text-6xl">
            Crie uma conta grátis
            </h1>
            <p className="max-w-md text-lg text-white">
            Você será direcionado para a página de cadastro
            </p>
              <Link
                className="bg-white text-[#6c5ce7] inline-flex items-center rounded-md bg-gray-900 px-4 py-2 text-sm font-medium shadow transition-colors hover:bg-gray-200 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-200 dark:focus-visible:ring-gray-300"
                href="https://www.everylang.ai/auth/register/"
              >
              Criar conta
              <ArrowRightIcon className="ml-2 h-4 w-4" />
            </Link>
              <Link
                className="text-white inline-flex items-center px-4 py-2 text-sm font-medium transition-colors hover:text-gray-200 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:text-gray-50 dark:text-gray-900 dark:hover:text-gray-200 dark:focus-visible:ring-gray-300"
                href="https://www.everylang.ai/auth/login/"
              >
              Já tenho uma conta
            </Link>
          </div>
        </section>
      </main>
      <Footer />
      <SupportDialog />
    </>
  )
}