/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/V1XUxH5hikV
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { CollapsibleTrigger, CollapsibleContent, Collapsible } from "@/components/ui/collapsible"
import { Avatar } from "@/components/ui/avatar"
import { CardContent, Card } from "@/components/ui/card"

export function LandingPageSchoolV2() {
  return (
    <>
      <header className="fixed top-0 left-0 z-10 w-full bg-white shadow-sm dark:bg-gray-950">
        <div className="container flex h-16 items-center justify-between px-4 md:px-6">
          <Link className="flex items-center" href="#">
            <MountainIcon className="h-6 w-6 text-[#6c5ce7]" />
            <span className="ml-2 text-lg font-semibold text-[#6c5ce7]">Acme</span>
          </Link>
          <Button className="rounded-md bg-[#6c5ce7] px-6 py-2 text-white hover:bg-[#5a4ec7] focus:outline-none focus:ring-2 focus:ring-[#6c5ce7] focus:ring-offset-2 dark:bg-[#6c5ce7] dark:hover:bg-[#5a4ec7] dark:focus:ring-[#6c5ce7]">
            Get Started
          </Button>
        </div>
      </header>
      <main>
        <section className="relative mt-16 bg-gradient-to-r from-[#6c5ce7] to-[#a29bfe] py-24 md:py-32 lg:py-40">
          <div className="container px-4 md:px-6">
            <div className="grid items-center gap-6 lg:grid-cols-2 lg:gap-12">
              <div className="space-y-4">
                <MountainIcon className="h-12 w-12 text-white" />
                <h1 className="text-4xl font-bold text-white sm:text-5xl md:text-6xl">Discover the Power of Our App</h1>
                <p className="text-lg text-white md:text-xl">
                  Experience the ultimate app for all your needs. Packed with features and designed for your
                  convenience.
                </p>
              </div>
              <div className="aspect-video w-full overflow-hidden rounded-xl" />
            </div>
          </div>
        </section>
        <section className="bg-white py-12 md:py-16 lg:py-20 dark:bg-gray-950">
          <div className="container px-4 md:px-6">
            <div className="grid items-center gap-6 lg:grid-cols-2 lg:gap-12">
              <div className="space-y-4">
                <h2 className="text-3xl font-bold text-[#6c5ce7] sm:text-4xl md:text-5xl">Pricing is Free</h2>
                <p className="text-lg text-gray-500 md:text-xl dark:text-gray-400">
                  Our app is completely free to use, with no hidden fees or subscriptions. Enjoy all the features
                  without any financial burden.
                </p>
              </div>
              <div className="aspect-video w-full overflow-hidden rounded-xl">
                <img
                  alt="Pricing"
                  className="h-full w-full object-cover"
                  height="450"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "800/450",
                    objectFit: "cover",
                  }}
                  width="800"
                />
              </div>
            </div>
          </div>
        </section>
        <section className="bg-gray-100 py-12 md:py-16 lg:py-20 dark:bg-gray-800">
          <div className="container px-4 md:px-6">
            <div className="grid items-center gap-6 lg:grid-cols-2 lg:gap-12">
              <div className="aspect-video w-full overflow-hidden rounded-xl">
                <img
                  alt="Benefits"
                  className="h-full w-full object-cover"
                  height="450"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "800/450",
                    objectFit: "cover",
                  }}
                  width="800"
                />
              </div>
              <div className="space-y-4">
                <h2 className="text-3xl font-bold text-[#6c5ce7] sm:text-4xl md:text-5xl">Unlock the Benefits</h2>
                <p className="text-lg text-gray-500 md:text-xl dark:text-gray-400">
                  Our app offers a wide range of features to enhance your experience. From seamless functionality to
                  personalized settings, we've got you covered.
                </p>
                <ul className="space-y-2 text-gray-500 dark:text-gray-400">
                  <li className="flex items-center">
                    <CheckIcon className="mr-2 h-5 w-5 text-[#6c5ce7]" />
                    Intuitive user interface
                  </li>
                  <li className="flex items-center">
                    <CheckIcon className="mr-2 h-5 w-5 text-[#6c5ce7]" />
                    Customizable settings
                  </li>
                  <li className="flex items-center">
                    <CheckIcon className="mr-2 h-5 w-5 text-[#6c5ce7]" />
                    Seamless integration
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </section>
        <section className="bg-white py-12 md:py-16 lg:py-20 dark:bg-gray-950">
          <div className="container px-4 md:px-6">
            <div className="grid items-center gap-6 lg:grid-cols-2 lg:gap-12">
              <div className="space-y-4">
                <h2 className="text-3xl font-bold text-[#6c5ce7] sm:text-4xl md:text-5xl">Designed for Your Needs</h2>
                <p className="text-lg text-gray-500 md:text-xl dark:text-gray-400">
                  Our app is built with your needs in mind, offering a seamless and intuitive experience. Discover how
                  it can simplify your daily tasks and enhance your productivity.
                </p>
                <Button className="rounded-md bg-[#6c5ce7] px-6 py-2 text-white hover:bg-[#5a4ec7] focus:outline-none focus:ring-2 focus:ring-[#6c5ce7] focus:ring-offset-2 dark:bg-[#6c5ce7] dark:hover:bg-[#5a4ec7] dark:focus:ring-[#6c5ce7]">
                  Learn More
                </Button>
              </div>
              <div className="aspect-video w-full overflow-hidden rounded-xl">
                <img
                  alt="Designed for Your Needs"
                  className="h-full w-full object-cover"
                  height="450"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "800/450",
                    objectFit: "cover",
                  }}
                  width="800"
                />
              </div>
            </div>
          </div>
        </section>
        <section className="bg-gray-100 py-12 md:py-16 lg:py-20 dark:bg-gray-800">
          <div className="container px-4 md:px-6">
            <div className="grid items-center gap-6 lg:grid-cols-2 lg:gap-12">
              <div className="aspect-video w-full overflow-hidden rounded-xl">
                <img
                  alt="Simplify Your Life"
                  className="h-full w-full object-cover"
                  height="450"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "800/450",
                    objectFit: "cover",
                  }}
                  width="800"
                />
              </div>
              <div className="space-y-4">
                <h2 className="text-3xl font-bold text-[#6c5ce7] sm:text-4xl md:text-5xl">Simplify Your Life</h2>
                <p className="text-lg text-gray-500 md:text-xl dark:text-gray-400">
                  Our app is designed to streamline your daily tasks and make your life easier. Enjoy a seamless
                  experience that adapts to your needs.
                </p>
                <Button className="rounded-md bg-[#6c5ce7] px-6 py-2 text-white hover:bg-[#5a4ec7] focus:outline-none focus:ring-2 focus:ring-[#6c5ce7] focus:ring-offset-2 dark:bg-[#6c5ce7] dark:hover:bg-[#5a4ec7] dark:focus:ring-[#6c5ce7]">
                  Download Now
                </Button>
              </div>
            </div>
          </div>
        </section>
        <section className="bg-white py-12 md:py-16 lg:py-20 dark:bg-gray-950">
          <div className="container px-4 md:px-6">
            <div className="space-y-6 text-center">
              <h2 className="text-3xl font-bold text-[#6c5ce7] sm:text-4xl md:text-5xl">Frequently Asked Questions</h2>
              <p className="text-lg text-gray-500 md:text-xl dark:text-gray-400">
                Got questions? We've got answers. Check out our FAQ section to learn more about our app.
              </p>
              <div className="grid gap-4 sm:grid-cols-2 md:grid-cols-3">
                <Collapsible>
                  <CollapsibleTrigger className="flex w-full items-center justify-between rounded-md bg-gray-100 px-4 py-3 text-lg font-medium text-gray-800 hover:bg-gray-200 focus:outline-none focus:ring-2 focus:ring-[#6c5ce7] focus:ring-offset-2 dark:bg-gray-800 dark:text-gray-200 dark:hover:bg-gray-700">
                    What features does the app offer?
                    <ChevronDownIcon className="h-5 w-5 transition-transform [&[data-state=open]]:rotate-180" />
                  </CollapsibleTrigger>
                  <CollapsibleContent className="rounded-md bg-gray-100 px-4 py-3 text-gray-500 dark:bg-gray-800 dark:text-gray-400">
                    Our app offers a wide range of features to enhance your experience, including intuitive user
                    interface, customizable settings, and seamless integration.
                  </CollapsibleContent>
                </Collapsible>
                <Collapsible>
                  <CollapsibleTrigger className="flex w-full items-center justify-between rounded-md bg-gray-100 px-4 py-3 text-lg font-medium text-gray-800 hover:bg-gray-200 focus:outline-none focus:ring-2 focus:ring-[#6c5ce7] focus:ring-offset-2 dark:bg-gray-800 dark:text-gray-200 dark:hover:bg-gray-700">
                    Is the app free to use?
                    <ChevronDownIcon className="h-5 w-5 transition-transform [&[data-state=open]]:rotate-180" />
                  </CollapsibleTrigger>
                  <CollapsibleContent className="rounded-md bg-gray-100 px-4 py-3 text-gray-500 dark:bg-gray-800 dark:text-gray-400">
                    Yes, our app is completely free to use, with no hidden fees or subscriptions. Enjoy all the features
                    without any financial burden.
                  </CollapsibleContent>
                </Collapsible>
                <Collapsible>
                  <CollapsibleTrigger className="flex w-full items-center justify-between rounded-md bg-gray-100 px-4 py-3 text-lg font-medium text-gray-800 hover:bg-gray-200 focus:outline-none focus:ring-2 focus:ring-[#6c5ce7] focus:ring-offset-2 dark:bg-gray-800 dark:text-gray-200 dark:hover:bg-gray-700">
                    How do I get started with the app?
                    <ChevronDownIcon className="h-5 w-5 transition-transform [&[data-state=open]]:rotate-180" />
                  </CollapsibleTrigger>
                  <CollapsibleContent className="rounded-md bg-gray-100 px-4 py-3 text-gray-500 dark:bg-gray-800 dark:text-gray-400">
                    Getting started with our app is easy. Simply download it from the app store, create an account, and
                    start exploring all the features.
                  </CollapsibleContent>
                </Collapsible>
              </div>
            </div>
          </div>
        </section>
        <section className="bg-gray-100 py-12 md:py-16 lg:py-20 dark:bg-gray-800">
          <div className="container px-4 md:px-6">
            <div className="space-y-6 text-center">
              <h2 className="text-3xl font-bold text-[#6c5ce7] sm:text-4xl md:text-5xl">What Our Users Say</h2>
              <p className="text-lg text-gray-500 md:text-xl dark:text-gray-400">
                Hear from our satisfied customers and see why they love our app.
              </p>
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-3">
                <Card className="bg-white shadow-sm dark:bg-gray-950">
                  <CardContent className="space-y-4">
                    <div className="flex items-center space-x-3">
                      <Avatar className="bg-[#6c5ce7] text-white">JD</Avatar>
                      <div>
                        <div className="font-medium">John Doe</div>
                        <div className="text-sm text-gray-500 dark:text-gray-400">CEO, Acme Inc.</div>
                      </div>
                    </div>
                    <p className="text-gray-500 dark:text-gray-400">
                      "I absolutely love this app! It has made my life so much easier. The features are amazing and the
                      user experience is top-notch."
                    </p>
                  </CardContent>
                </Card>
                <Card className="bg-white shadow-sm dark:bg-gray-950">
                  <CardContent className="space-y-4">
                    <div className="flex items-center space-x-3">
                      <Avatar className="bg-[#6c5ce7] text-white">SM</Avatar>
                      <div>
                        <div className="font-medium">Sarah Miller</div>
                        <div className="text-sm text-gray-500 dark:text-gray-400">Designer, Acme Inc.</div>
                      </div>
                    </div>
                    <p className="text-gray-500 dark:text-gray-400">
                      "This app has been a game-changer for me. It's so intuitive and easy to use, and the customization
                      options are fantastic."
                    </p>
                  </CardContent>
                </Card>
                <Card className="bg-white shadow-sm dark:bg-gray-950">
                  <CardContent className="space-y-4">
                    <div className="flex items-center space-x-3" />
                  </CardContent>
                </Card>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  )
}

function CheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  )
}


function ChevronDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  )
}


function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}
