/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/CvdTfp0rdps
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { CollapsibleTrigger, CollapsibleContent, Collapsible } from "@/components/ui/collapsible"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { Card } from "@/components/ui/card"

export function LandingPageHome() {
  return (
    <>
      <header className="fixed top-0 left-0 right-0 z-50 flex h-16 items-center justify-between bg-white px-6 shadow-sm dark:bg-gray-950">
        <Link className="flex items-center gap-2" href="#">
          <MountainIcon className="h-6 w-6" />
          <span className="text-lg font-semibold">Acme App</span>
        </Link>
        <Link
          className="inline-flex h-9 items-center justify-center rounded-md bg-gray-900 px-4 py-2 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
          href="#"
        >
          Download
        </Link>
      </header>
      <main>
        <section className="relative flex h-[80vh] items-center justify-center bg-gradient-to-r from-[#4e54c8] to-[#8f94fb] px-6 pt-20 md:pt-24 lg:pt-32">
          <div className="z-10 max-w-2xl text-center">
            <MountainIcon className="mx-auto h-16 w-16 text-white" />
            <h1 className="mt-6 text-4xl font-bold tracking-tighter text-white sm:text-5xl md:text-6xl">Acme App</h1>
            <p className="mt-4 text-lg text-gray-200 md:text-xl">
              The ultimate app for all your needs. Download now and experience the future.
            </p>
            <Link
              className="mt-8 inline-flex h-10 items-center justify-center rounded-md bg-white px-6 py-2 text-sm font-medium text-gray-900 shadow-sm transition-colors hover:bg-gray-100 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-950 dark:text-gray-50 dark:hover:bg-gray-800 dark:focus-visible:ring-gray-300"
              href="#"
            >
              Download App
            </Link>
          </div>
          <div className="absolute inset-0 -z-10 bg-gradient-to-r from-[#4e54c8] to-[#8f94fb] opacity-70 blur-[100px]" />
        </section>
        <section className="py-12 md:py-24 lg:py-32">
          <div className="container grid items-center gap-6 px-4 md:px-6 lg:grid-cols-2 lg:gap-12">
            <div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Seamless Collaboration</h2>
              <p className="mt-4 text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Acme App makes it easy for your team to work together. Share files, communicate, and stay organized all
                in one place.
              </p>
            </div>
            <img
              alt="Seamless Collaboration"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
              height="310"
              src="/placeholder.svg"
              width="550"
            />
          </div>
        </section>
        <section className="py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
          <div className="container grid items-center gap-6 px-4 md:px-6 lg:grid-cols-2 lg:gap-12">
            <img
              alt="Advanced Analytics"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
              height="310"
              src="/placeholder.svg"
              width="550"
            />
            <div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Advanced Analytics</h2>
              <p className="mt-4 text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Acme App provides powerful analytics to help you make data-driven decisions. Track user behavior,
                measure performance, and optimize your app.
              </p>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-24 lg:py-32">
          <div className="container grid items-center gap-6 px-4 md:px-6 lg:grid-cols-2 lg:gap-12">
            <div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Secure and Scalable</h2>
              <p className="mt-4 text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Acme App is built with security and scalability in mind. Your data is safe with us, and your app can
                grow as your business does.
              </p>
            </div>
            <img
              alt="Secure and Scalable"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
              height="310"
              src="/placeholder.svg"
              width="550"
            />
          </div>
        </section>
        <section className="py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="mx-auto max-w-2xl text-center">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                Frequently Asked Questions
              </h2>
              <p className="mt-4 text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Get answers to the most common questions about Acme App.
              </p>
            </div>
            <div className="mt-10 grid gap-4">
              <Collapsible>
                <CollapsibleTrigger className="flex w-full items-center justify-between rounded-md bg-gray-100 px-4 py-3 text-lg font-medium transition-colors hover:bg-gray-200 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 dark:bg-gray-800 dark:hover:bg-gray-700">
                  What is Acme App?
                  <ChevronRightIcon className="h-5 w-5 transition-transform [&[data-state=open]]:rotate-90" />
                </CollapsibleTrigger>
                <CollapsibleContent className="rounded-md bg-gray-100 px-4 py-3 text-gray-500 dark:bg-gray-800 dark:text-gray-400">
                  Acme App is a powerful platform that helps you manage your business and collaborate with your team. It
                  offers a wide range of features, including file sharing, communication tools, and advanced analytics.
                </CollapsibleContent>
              </Collapsible>
              <Collapsible>
                <CollapsibleTrigger className="flex w-full items-center justify-between rounded-md bg-gray-100 px-4 py-3 text-lg font-medium transition-colors hover:bg-gray-200 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 dark:bg-gray-800 dark:hover:bg-gray-700">
                  How much does Acme App cost?
                  <ChevronRightIcon className="h-5 w-5 transition-transform [&[data-state=open]]:rotate-90" />
                </CollapsibleTrigger>
                <CollapsibleContent className="rounded-md bg-gray-100 px-4 py-3 text-gray-500 dark:bg-gray-800 dark:text-gray-400">
                  Acme App offers a range of pricing plans to fit your needs. Our basic plan is free, and our premium
                  plans start at $9 per user per month. You can learn more about our pricing on the Pricing page.
                </CollapsibleContent>
              </Collapsible>
              <Collapsible>
                <CollapsibleTrigger className="flex w-full items-center justify-between rounded-md bg-gray-100 px-4 py-3 text-lg font-medium transition-colors hover:bg-gray-200 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 dark:bg-gray-800 dark:hover:bg-gray-700">
                  Is Acme App secure?
                  <ChevronRightIcon className="h-5 w-5 transition-transform [&[data-state=open]]:rotate-90" />
                </CollapsibleTrigger>
                <CollapsibleContent className="rounded-md bg-gray-100 px-4 py-3 text-gray-500 dark:bg-gray-800 dark:text-gray-400">
                  Yes, Acme App is built with security in mind. We use the latest encryption technologies to protect
                  your data, and we have strict access controls to ensure that only authorized users can access your
                  information.
                </CollapsibleContent>
              </Collapsible>
              <Collapsible>
                <CollapsibleTrigger className="flex w-full items-center justify-between rounded-md bg-gray-100 px-4 py-3 text-lg font-medium transition-colors hover:bg-gray-200 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 dark:bg-gray-800 dark:hover:bg-gray-700">
                  How do I get started with Acme App?
                  <ChevronRightIcon className="h-5 w-5 transition-transform [&[data-state=open]]:rotate-90" />
                </CollapsibleTrigger>
                <CollapsibleContent className="rounded-md bg-gray-100 px-4 py-3 text-gray-500 dark:bg-gray-800 dark:text-gray-400">
                  Getting started with Acme App is easy. Simply download the app from the App Store or Google Play,
                  create an account, and you're ready to go. Our intuitive interface and step-by-step guides will help
                  you get up and running in no time.
                </CollapsibleContent>
              </Collapsible>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
          <div className="container px-4 md:px-6">
            <div className="mx-auto max-w-2xl text-center">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">What Our Users Say</h2>
              <p className="mt-4 text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Hear from our satisfied customers about their experience with Acme App.
              </p>
            </div>
            <div className="mt-10 grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
              <Card className="bg-white p-6 shadow-sm transition-colors hover:bg-gray-100 dark:bg-gray-950 dark:hover:bg-gray-800">
                <div className="space-y-4">
                  <div className="flex items-center gap-4">
                    <Avatar>
                      <AvatarImage src="/placeholder-avatar.svg" />
                      <AvatarFallback>JD</AvatarFallback>
                    </Avatar>
                    <div>
                      <div className="text-lg font-medium">John Doe</div>
                      <div className="text-sm text-gray-500 dark:text-gray-400">CEO, Acme Inc.</div>
                    </div>
                  </div>
                  <p className="text-gray-500 dark:text-gray-400">
                    "Acme App has been a game-changer for our business. The collaboration features have made it so much
                    easier for our team to work together, and the analytics have been invaluable in helping us make
                    data-driven decisions."
                  </p>
                </div>
              </Card>
              <Card className="bg-white p-6 shadow-sm transition-colors hover:bg-gray-100 dark:bg-gray-950 dark:hover:bg-gray-800">
                <div className="space-y-4">
                  <div className="flex items-center gap-4">
                    <Avatar>
                      <AvatarImage src="/placeholder-avatar.svg" />
                      <AvatarFallback>JD</AvatarFallback>
                    </Avatar>
                    <div>
                      <div className="text-lg font-medium">Jane Doe</div>
                      <div className="text-sm text-gray-500 dark:text-gray-400">Product Manager, Acme Inc.</div>
                    </div>
                  </div>
                  <p className="text-gray-500 dark:text-gray-400">
                    "I've been using Acme App for over a year now, and I can honestly say it's the best tool I've ever
                    used for managing my team and projects. The user experience is top-notch, and the support team is
                    always there to help when I need it."
                  </p>
                </div>
              </Card>
              <Card className="bg-white p-6 shadow-sm transition-colors hover:bg-gray-100 dark:bg-gray-950 dark:hover:bg-gray-800">
                <div className="space-y-4">
                  <div className="flex items-center gap-4">
                    <Avatar>
                      <AvatarImage src="/placeholder-avatar.svg" />
                      <AvatarFallback>JD</AvatarFallback>
                    </Avatar>
                    <div>
                      <div className="text-lg font-medium">Bob Smith</div>
                      <div className="text-sm text-gray-500 dark:text-gray-400">Developer, Acme Inc.</div>
                    </div>
                  </div>
                  <p className="text-gray-500 dark:text-gray-400">
                    "Acme App has been a game-changer for our development team. The built-in collaboration tools and
                    analytics have helped us work more efficiently and make better decisions. I'd highly recommend it to
                    any team looking to improve their workflow."
                  </p>
                </div>
              </Card>
            </div>
          </div>
        </section>
      </main>
    </>
  )
}

function ChevronRightIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}


function MountainIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}
