/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/jup0uYLi2AS
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Cormorant_Garamond } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { CollapsibleTrigger, CollapsibleContent, Collapsible } from "@/components/ui/collapsible"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { themeColor } from '@/layout/colors'

export function LandingPageSchool() {
  return (
    <>
      <header className="fixed top-0 left-0 right-0 z-50 flex h-16 w-full items-center justify-between bg-white px-4 shadow-sm dark:bg-gray-950">
        <Link className="flex items-center gap-2" href="#">
          <MountainIcon className={`h-6 w-6 text-[${themeColor.main}]`} />
          <span className={`text-lg font-semibold text-[${themeColor.main}]`}>Acme App</span>
        </Link>
        <Button className={`bg-[${themeColor.main}] text-white hover:bg-[${themeColor.dark}]`} >
          Get Started
        </Button>
      </header>
      <main>
        <section className="relative mt-16 h-[80vh] w-full bg-[url(/hero-bg.jpg)] bg-cover bg-center bg-no-repeat">
          <div className="absolute inset-0 bg-gradient-to-r from-[#6c5ce7]/80 to-[#9b59b6]/80 backdrop-blur-lg" />
          <div className="container mx-auto flex h-full items-center justify-center px-4">
            <div className="relative z-10 max-w-2xl text-center text-white">
              <div className="mb-4 flex items-center justify-center">
                <MountainIcon className="h-12 w-12" />
                <span className="ml-2 text-3xl font-bold">Acme App</span>
              </div>
              <h1 className="mb-4 text-4xl font-bold sm:text-5xl">The Ultimate App for Your Needs</h1>
              <p className="mb-8 text-lg">Experience the power of our app and transform the way you work.</p>
              <div className="aspect-video w-full rounded-lg" />
            </div>
          </div>
        </section>
        <section className="bg-[#6c5ce7] py-12 text-white">
          <div className="container mx-auto px-4">
            <div className="flex items-center justify-center">
              <GiftIcon className="mr-2 h-6 w-6" />
              <h2 className="text-2xl font-bold">It's Free!</h2>
            </div>
          </div>
        </section>
        <section className="py-12">
          <div className="container mx-auto px-4">
            <div className="grid gap-8 md:grid-cols-2">
              <div>
                <h2 className="mb-4 text-2xl font-bold text-[#6c5ce7]">Streamline Your Workflow</h2>
                <p className="text-gray-600">
                  Our app is designed to help you work smarter, not harder. With our intuitive interface and powerful
                  features, you'll be able to streamline your workflow and boost your productivity.
                </p>
              </div>
              <div>
                <h2 className="mb-4 text-2xl font-bold text-[#6c5ce7]">Collaborate with Ease</h2>
                <p className="text-gray-600">
                  Seamlessly collaborate with your team, share files, and communicate in real-time. Our app makes it
                  easy to stay connected and on top of your projects.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className="bg-[#f5f5f5] py-12">
          <div className="container mx-auto px-4">
            <div className="grid gap-8 md:grid-cols-2">
              <div className="order-2 md:order-1">
                <h2 className="mb-4 text-2xl font-bold text-[#6c5ce7]">Powerful Analytics</h2>
                <p className="text-gray-600">
                  Gain valuable insights into your data with our advanced analytics. Track your progress, identify
                  trends, and make informed decisions to drive your business forward.
                </p>
              </div>
              <div className="order-1 md:order-2">
                <img
                  alt="Analytics"
                  className="rounded-lg"
                  height={400}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "600/400",
                    objectFit: "cover",
                  }}
                  width={600}
                />
              </div>
            </div>
          </div>
        </section>
        <section className="py-12">
          <div className="container mx-auto px-4">
            <div className="grid gap-8 md:grid-cols-2">
              <div>
                <img
                  alt="Mobile App"
                  className="rounded-lg"
                  height={400}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "600/400",
                    objectFit: "cover",
                  }}
                  width={600}
                />
              </div>
              <div>
                <h2 className="mb-4 text-2xl font-bold text-[#6c5ce7]">Mobile-Friendly Design</h2>
                <p className="text-gray-600">
                  Our app is designed with a mobile-first approach, ensuring a seamless experience on any device. Stay
                  connected and productive on the go.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className="bg-[#f5f5f5] py-12">
          <div className="container mx-auto px-4">
            <h2 className="mb-8 text-center text-2xl font-bold text-[#6c5ce7]">Frequently Asked Questions</h2>
            <div className="grid gap-4">
              <Collapsible>
                <CollapsibleTrigger className="flex items-center justify-between rounded-lg bg-white px-4 py-3 shadow-sm transition-colors hover:bg-gray-100">
                  <span className="text-lg font-medium">What features does the app offer?</span>
                  <ChevronDownIcon className="h-5 w-5 transition-transform [&[data-state=open]]:rotate-180" />
                </CollapsibleTrigger>
                <CollapsibleContent className="bg-white px-4 py-3 shadow-sm">
                  <p className="text-gray-600">
                    Our app offers a wide range of features to help you streamline your workflow, including task
                    management, project collaboration, and advanced analytics.
                  </p>
                </CollapsibleContent>
              </Collapsible>
              <Collapsible>
                <CollapsibleTrigger className="flex items-center justify-between rounded-lg bg-white px-4 py-3 shadow-sm transition-colors hover:bg-gray-100">
                  <span className="text-lg font-medium">Is the app available on mobile devices?</span>
                  <ChevronDownIcon className="h-5 w-5 transition-transform [&[data-state=open]]:rotate-180" />
                </CollapsibleTrigger>
                <CollapsibleContent className="bg-white px-4 py-3 shadow-sm">
                  <p className="text-gray-600">
                    Yes, our app is available on both iOS and Android devices, allowing you to stay connected and
                    productive on the go.
                  </p>
                </CollapsibleContent>
              </Collapsible>
              <Collapsible>
                <CollapsibleTrigger className="flex items-center justify-between rounded-lg bg-white px-4 py-3 shadow-sm transition-colors hover:bg-gray-100">
                  <span className="text-lg font-medium">Is there a free trial or demo available?</span>
                  <ChevronDownIcon className="h-5 w-5 transition-transform [&[data-state=open]]:rotate-180" />
                </CollapsibleTrigger>
                <CollapsibleContent className="bg-white px-4 py-3 shadow-sm">
                  <p className="text-gray-600">
                    Yes, we offer a free trial period so you can explore the app's features and see if it's the right
                    fit for your needs. You can also request a demo to get a personalized walkthrough.
                  </p>
                </CollapsibleContent>
              </Collapsible>
            </div>
          </div>
        </section>
        <section className="py-12">
          <div className="container mx-auto px-4">
            <h2 className="mb-8 text-center text-2xl font-bold text-[#6c5ce7]">What Our Users Say</h2>
            <div className="grid gap-4 sm:grid-cols-2 md:grid-cols-3">
              <div className="rounded-lg bg-white p-4 shadow-sm">
                <div className="mb-4 flex items-center">
                  <Avatar>
                    <AvatarImage src="/avatar1.jpg" />
                    <AvatarFallback>JD</AvatarFallback>
                  </Avatar>
                  <div className="ml-3">
                    <div className="text-lg font-medium">John Doe</div>
                    <div className="text-gray-500">CEO, Acme Inc.</div>
                  </div>
                </div>
                <p className="text-gray-600">
                  "I've been using this app for months and it has completely transformed the way I work. Highly
                  recommended!"
                </p>
              </div>
              <div className="rounded-lg bg-white p-4 shadow-sm">
                <div className="mb-4 flex items-center">
                  <Avatar>
                    <AvatarImage src="/avatar2.jpg" />
                    <AvatarFallback>JA</AvatarFallback>
                  </Avatar>
                  <div className="ml-3">
                    <div className="text-lg font-medium">Jane Appleseed</div>
                    <div className="text-gray-500">Project Manager, Acme Inc.</div>
                  </div>
                </div>
                <p className="text-gray-600">
                  "This app has been a game-changer for my team. The collaboration features are top-notch."
                </p>
              </div>
              <div className="rounded-lg bg-white p-4 shadow-sm">
                <div className="mb-4 flex items-center">
                  <Avatar>
                    <AvatarImage src="/avatar3.jpg" />
                    <AvatarFallback>SM</AvatarFallback>
                  </Avatar>
                  <div className="ml-3">
                    <div className="text-lg font-medium">Sarah Miller</div>
                    <div className="text-gray-500">Marketing Manager, Acme Inc.</div>
                  </div>
                </div>
                <p className="text-gray-600">
                  "I love how user-friendly and intuitive this app is. It's definitely a must-have for any business."
                </p>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-[#6c5ce7] py-8 text-white">
        <div className="container mx-auto px-4">
          <div className="grid gap-8 md:grid-cols-2">
            <div>
              <div className="mb-4 flex items-center">
                <MountainIcon className="mr-2 h-6 w-6" />
                <span className="text-lg font-semibold">Acme App</span>
              </div>
              <p className="mb-4 text-gray-300">Stay connected with us on social media.</p>
              <div className="flex items-center gap-4">
                <Link className="text-gray-300 hover:text-white" href="#">
                  <TwitterIcon className="h-6 w-6" />
                </Link>
                <Link className="text-gray-300 hover:text-white" href="#">
                  <FacebookIcon className="h-6 w-6" />
                </Link>
                <Link className="text-gray-300 hover:text-white" href="#">
                  <InstagramIcon className="h-6 w-6" />
                </Link>
                <Link className="text-gray-300 hover:text-white" href="#">
                  <LinkedinIcon className="h-6 w-6" />
                </Link>
              </div>
            </div>
            <div>
              <h3 className="mb-4 text-lg font-bold">Contact Us</h3>
              <p className="mb-2 flex items-center">
                <MailIcon className="mr-2 h-5 w-5" />
                <a href="#">support@acmeapp.com</a>
              </p>
              <p className="mb-2 flex items-center">
                <PhoneIcon className="mr-2 h-5 w-5" />
                <a href="#">+1 (234) 567-890</a>
              </p>
              <div className="mt-4">
                <Link className="mr-4 text-gray-300 hover:text-white" href="#">
                  Terms of Service
                </Link>
                <Link className="text-gray-300 hover:text-white" href="#">
                  Privacy Policy
                </Link>
              </div>
            </div>
          </div>
        </div>
      </footer>
    </>
  )
}

function ChevronDownIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  )
}


function FacebookIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  )
}


function GiftIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect x="3" y="8" width="18" height="4" rx="1" />
      <path d="M12 8v13" />
      <path d="M19 12v7a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2v-7" />
      <path d="M7.5 8a2.5 2.5 0 0 1 0-5A4.8 8 0 0 1 12 8a4.8 8 0 0 1 4.5-5 2.5 2.5 0 0 1 0 5" />
    </svg>
  )
}


function InstagramIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  )
}


function LinkedinIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}


function MailIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  )
}


function MountainIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function PhoneIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
    </svg>
  )
}


function TwitterIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}
