/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/5SatxPAiQuq
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Rubik } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"

export function Pricing() {
  return (
    <>
      <header className="fixed top-0 left-0 right-0 z-50 flex h-16 w-full items-center justify-between bg-white px-4 shadow-sm dark:bg-gray-950">
        <Link className="flex items-center gap-2" href="#">
          <MountainIcon className="h-6 w-6 text-[#6b5b95]" />
          <span className="text-lg font-semibold text-[#6b5b95]">Acme Inc</span>
        </Link>
        <Button
          className="rounded-md bg-[#6b5b95] px-4 py-2 text-white hover:bg-[#5a4d7c] focus:outline-none focus:ring-2 focus:ring-[#6b5b95] focus:ring-offset-2 dark:bg-[#6b5b95] dark:hover:bg-[#5a4d7c] dark:focus:ring-[#6b5b95]"
          variant="primary"
        >
          Get Started
        </Button>
      </header>
      <main>
        <section className="relative mt-16 h-[80vh] w-full bg-gradient-to-r from-[#6b5b95] to-[#9370db] bg-[url(/hero-bg.jpg)] bg-cover bg-center bg-no-repeat bg-blend-multiply">
          <div className="container mx-auto flex h-full items-center justify-center">
            <div className="text-center text-white">
              <MountainIcon className="mx-auto h-16 w-16" />
              <h1 className="mt-4 text-4xl font-bold">Welcome to Acme Inc</h1>
              <p className="mt-4 text-lg">Discover the best products and services for your business.</p>
            </div>
          </div>
        </section>
        <section className="bg-white py-12 dark:bg-gray-950">
          <div className="container mx-auto">
            <h2 className="mb-8 text-center text-3xl font-bold text-[#6b5b95]">Pricing</h2>
            <div className="grid grid-cols-1 gap-8 sm:grid-cols-2 md:grid-cols-4">
              <div className="rounded-lg border border-gray-200 p-6 dark:border-gray-800 dark:border-gray-800">
                <h3 className="text-xl font-bold">Feature 1</h3>
                <p className="mt-2 text-gray-500 dark:text-gray-400">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                </p>
              </div>
              <div className="rounded-lg border border-gray-200 p-6 dark:border-gray-800 dark:border-gray-800">
                <h3 className="text-xl font-bold">Feature 2</h3>
                <p className="mt-2 text-gray-500 dark:text-gray-400">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                </p>
              </div>
              <div className="rounded-lg border border-gray-200 p-6 dark:border-gray-800 dark:border-gray-800">
                <h3 className="text-xl font-bold">Feature 3</h3>
                <p className="mt-2 text-gray-500 dark:text-gray-400">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                </p>
              </div>
              <div className="rounded-lg border border-gray-200 p-6 dark:border-gray-800 dark:border-gray-800">
                <h3 className="text-xl font-bold">Feature 4</h3>
                <p className="mt-2 text-gray-500 dark:text-gray-400">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                </p>
              </div>
            </div>
            <div className="mt-8 flex flex-col items-center justify-center space-y-4 sm:flex-row sm:space-y-0 sm:space-x-4">
              <div className="rounded-lg border border-gray-200 bg-white p-6 dark:border-gray-800 dark:bg-gray-950 dark:border-gray-800">
                <h3 className="text-2xl font-bold text-[#6b5b95]">Monthly</h3>
                <p className="mt-2 text-4xl font-bold">R$ 29.99</p>
                <Button
                  className="mt-4 w-full rounded-md bg-[#6b5b95] px-4 py-2 text-white hover:bg-[#5a4d7c] focus:outline-none focus:ring-2 focus:ring-[#6b5b95] focus:ring-offset-2 dark:bg-[#6b5b95] dark:hover:bg-[#5a4d7c] dark:focus:ring-[#6b5b95]"
                  variant="primary"
                >
                  Subscribe
                </Button>
              </div>
              <div className="rounded-lg border border-gray-200 bg-white p-6 dark:border-gray-800 dark:bg-gray-950 dark:border-gray-800">
                <h3 className="text-2xl font-bold text-[#6b5b95]">Yearly</h3>
                <p className="mt-2 text-4xl font-bold">R$ 179.94</p>
                <p className="mt-2 text-sm text-gray-500 dark:text-gray-400">50% off, most popular</p>
                <Button
                  className="mt-4 w-full rounded-md bg-[#6b5b95] px-4 py-2 text-white hover:bg-[#5a4d7c] focus:outline-none focus:ring-2 focus:ring-[#6b5b95] focus:ring-offset-2 dark:bg-[#6b5b95] dark:hover:bg-[#5a4d7c] dark:focus:ring-[#6b5b95]"
                  variant="primary"
                >
                  Subscribe
                </Button>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-[#6b5b95] py-8 text-white">
        <div className="container mx-auto flex flex-col items-center justify-between space-y-4 sm:flex-row sm:space-y-0">
          <div className="flex items-center space-x-4">
            <Link className="hover:underline" href="#">
              <FacebookIcon className="h-6 w-6" />
            </Link>
            <Link className="hover:underline" href="#">
              <TwitterIcon className="h-6 w-6" />
            </Link>
            <Link className="hover:underline" href="#">
              <InstagramIcon className="h-6 w-6" />
            </Link>
          </div>
          <div className="flex items-center space-x-4">
            <a className="hover:underline" href="#">
              info@acme.com
            </a>
            <a className="hover:underline" href="#">
              +123 456 789
            </a>
          </div>
          <div className="flex items-center space-x-4">
            <Link className="hover:underline" href="#">
              Terms of Service
            </Link>
            <Link className="hover:underline" href="#">
              Privacy Policy
            </Link>
          </div>
        </div>
      </footer>
    </>
  )
}

function FacebookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  )
}


function InstagramIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  )
}


function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function TwitterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}
