/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/UuDrRUdn98y
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Cormorant_Garamond } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"

export function PricingV2() {
  return (
    <>
      <header className="fixed top-0 left-0 right-0 z-10 flex h-16 items-center justify-between bg-white px-4 md:px-6 shadow-sm dark:bg-gray-950">
        <Link className="flex items-center" href="#">
          <MountainIcon className="h-6 w-6 text-[#6b5b95]" />
          <span className="ml-2 text-lg font-semibold text-[#6b5b95]">Acme Inc</span>
        </Link>
        <Button className="rounded-md bg-[#6b5b95] px-4 py-2 text-white hover:bg-[#6b5b95]/90" >
          Get Started
        </Button>
      </header>
      <main>
        <section className="relative flex h-[calc(100vh-4rem)] flex-col items-center justify-center bg-[url(/hero-bg.jpg)] bg-cover bg-center bg-no-repeat">
          <div className="absolute inset-0 bg-gradient-to-br from-[#6b5b95]/50 to-[#6b5b95]/30 backdrop-blur-sm" />
          <div className="relative z-10 space-y-4 text-center">
            <MountainIcon className="h-12 w-12 text-[#6b5b95]" />
            <h1 className="text-4xl font-bold text-white sm:text-5xl md:text-6xl">Acme Inc</h1>
            <p className="max-w-md text-lg text-gray-200 md:text-xl">
              Unleash your potential with our cutting-edge solutions.
            </p>
          </div>
        </section>
        <section className="bg-white py-12 md:py-24 lg:py-32 dark:bg-gray-950">
          <div className="container">
            <div className="mx-auto max-w-4xl space-y-8 text-center">
              <h2 className="text-3xl font-bold text-[#6b5b95] sm:text-4xl md:text-5xl">Pricing</h2>
              <p className="text-gray-500 dark:text-gray-400 md:text-xl">Choose the plan that fits your needs.</p>
              <div className="grid grid-cols-1 gap-6 sm:grid-cols-2">
                <Card className="rounded-lg border border-gray-200 bg-white p-6 shadow-sm dark:border-gray-800 dark:bg-gray-900 dark:border-gray-800">
                  <CardHeader>
                    <CardTitle className="text-2xl font-bold">Monthly</CardTitle>
                    <CardDescription className="text-4xl font-bold text-[#6b5b95]">R$ 29.99</CardDescription>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    <div className="flex items-center gap-2">
                      <CheckIcon className="h-5 w-5 text-[#6b5b95]" />
                      <h3 className="text-lg font-medium">Unlimited Users</h3>
                    </div>
                    <div className="flex items-center gap-2">
                      <CheckIcon className="h-5 w-5 text-[#6b5b95]" />
                      <h3 className="text-lg font-medium">Unlimited Storage</h3>
                    </div>
                    <div className="flex items-center gap-2">
                      <CheckIcon className="h-5 w-5 text-[#6b5b95]" />
                      <h3 className="text-lg font-medium">Unlimited Bandwidth</h3>
                    </div>
                    <div className="flex items-center gap-2">
                      <CheckIcon className="h-5 w-5 text-[#6b5b95]" />
                      <h3 className="text-lg font-medium">Custom Domains</h3>
                    </div>
                    <div className="flex items-center gap-2">
                      <CheckIcon className="h-5 w-5 text-[#6b5b95]" />
                      <h3 className="text-lg font-medium">Advanced Analytics</h3>
                    </div>
                    <div className="flex items-center gap-2">
                      <CheckIcon className="h-5 w-5 text-[#6b5b95]" />
                      <h3 className="text-lg font-medium">24/7 Support</h3>
                    </div>
                    <div className="flex items-center gap-2">
                      <CheckIcon className="h-5 w-5 text-[#6b5b95]" />
                      <h3 className="text-lg font-medium">Automated Backups</h3>
                    </div>
                  </CardContent>
                  <CardFooter>
                    <Button
                      className="w-full rounded-md bg-[#6b5b95] px-4 py-2 text-white hover:bg-[#6b5b95]/90"
                    >
                      Get Started
                    </Button>
                  </CardFooter>
                </Card>
                <Card className="rounded-lg border border-gray-200 border-[#6b5b95] bg-white p-6 shadow-sm dark:border-gray-800 dark:bg-gray-900 dark:border-gray-800">
                  <CardHeader>
                    <div className="flex items-center justify-between">
                      <CardTitle className="text-2xl font-bold">Annually</CardTitle>
                      <div className="rounded-md bg-[#6b5b95] px-2 py-1 text-sm font-medium text-white">
                        Most popular
                      </div>
                    </div>
                    <CardDescription className="text-4xl font-bold text-[#6b5b95]">
                      R$ 179.94
                      <span className="text-lg font-medium text-gray-500 line-through dark:text-gray-400">
                        R$ 359.88
                      </span>
                    </CardDescription>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    <div className="flex items-center gap-2">
                      <CheckIcon className="h-5 w-5 text-[#6b5b95]" />
                      <h3 className="text-lg font-medium">Unlimited Users</h3>
                    </div>
                    <div className="flex items-center gap-2">
                      <CheckIcon className="h-5 w-5 text-[#6b5b95]" />
                      <h3 className="text-lg font-medium">Unlimited Storage</h3>
                    </div>
                    <div className="flex items-center gap-2">
                      <CheckIcon className="h-5 w-5 text-[#6b5b95]" />
                      <h3 className="text-lg font-medium">Unlimited Bandwidth</h3>
                    </div>
                    <div className="flex items-center gap-2">
                      <CheckIcon className="h-5 w-5 text-[#6b5b95]" />
                      <h3 className="text-lg font-medium">Custom Domains</h3>
                    </div>
                    <div className="flex items-center gap-2">
                      <CheckIcon className="h-5 w-5 text-[#6b5b95]" />
                      <h3 className="text-lg font-medium">Advanced Analytics</h3>
                    </div>
                    <div className="flex items-center gap-2">
                      <CheckIcon className="h-5 w-5 text-[#6b5b95]" />
                      <h3 className="text-lg font-medium">24/7 Support</h3>
                    </div>
                    <div className="flex items-center gap-2">
                      <CheckIcon className="h-5 w-5 text-[#6b5b95]" />
                      <h3 className="text-lg font-medium">Automated Backups</h3>
                    </div>
                  </CardContent>
                  <CardFooter>
                    <Button
                      className="w-full rounded-md bg-[#6b5b95] px-4 py-2 text-white hover:bg-[#6b5b95]/90"
                    >
                      Get Started
                    </Button>
                  </CardFooter>
                </Card>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-[#6b5b95] py-8 text-white">
        <div className="container">
          <div className="mx-auto max-w-4xl space-y-6">
            <div className="flex flex-col items-center justify-between gap-4 sm:flex-row">
              <div className="flex items-center gap-2">
                <MountainIcon className="h-6 w-6" />
                <span className="text-lg font-semibold">Acme Inc</span>
              </div>
              <div className="flex items-center gap-4">
                <Link className="hover:underline" href="#">
                  <FacebookIcon className="h-6 w-6" />
                </Link>
                <Link className="hover:underline" href="#">
                  <TwitterIcon className="h-6 w-6" />
                </Link>
                <Link className="hover:underline" href="#">
                  <InstagramIcon className="h-6 w-6" />
                </Link>
                <Link className="hover:underline" href="#">
                  <LinkedinIcon className="h-6 w-6" />
                </Link>
              </div>
            </div>
            <div className="flex flex-col items-center justify-between gap-4 sm:flex-row">
              <div className="flex items-center gap-2">
                <MailIcon className="h-6 w-6" />
                <a className="hover:underline" href="#">
                  info@acme.com
                </a>
              </div>
              <div className="flex items-center gap-2">
                <PhoneIcon className="h-6 w-6" />
                <a className="hover:underline" href="#">
                  +1 (234) 567-890
                </a>
              </div>
            </div>
            <div className="flex flex-col items-center justify-between gap-4 sm:flex-row">
              <Link className="hover:underline" href="#">
                Terms of Service
              </Link>
              <Link className="hover:underline" href="#">
                Privacy Policy
              </Link>
            </div>
            <p className="text-center text-sm">© 2024 Acme Inc. All rights reserved.</p>
          </div>
        </div>
      </footer>
    </>
  )
}

function CheckIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  )
}


function FacebookIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  )
}


function InstagramIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  )
}


function LinkedinIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}


function MailIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  )
}


function MountainIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function PhoneIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
    </svg>
  )
}


function TwitterIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}
