/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/AxxeihdFVcp
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"

export function ScoreCard() {
  return (
    <div className="flex justify-center items-center h-screen">
      <Card className="w-full max-w-md">
        <CardHeader className="flex flex-col items-center gap-4 pb-6">
          <div className="flex items-center gap-2">
            <MicIcon className="h-6 w-6 text-gray-500 dark:text-gray-400" />
            <CardTitle className="text-lg font-medium">Pronunciation Score</CardTitle>
          </div>
          <div className="flex items-center gap-2 text-2xl font-bold">
            <span>82</span>
            <span className="text-4xl">🎉</span>
          </div>
        </CardHeader>
        <CardContent>
          <div className="relative h-4 w-full rounded-full bg-gray-200 dark:bg-gray-800">
            <div className="absolute inset-0 flex items-center justify-between px-2">
              <div className="text-xs text-gray-500 dark:text-gray-400">Bad</div>
              <div className="text-xs text-gray-500 dark:text-gray-400">Nice</div>
              <div className="text-xs text-gray-500 dark:text-gray-400">Good</div>
              <div className="text-xs text-gray-500 dark:text-gray-400">Excelente</div>
            </div>
            <div
              className="h-full rounded-full bg-gradient-to-r from-[#FF6B6B] to-[#FFC93C] to-[#9BDD7C] to-[#57CC99]"
              style={{
                width: "82%",
              }}
            />
          </div>
        </CardContent>
      </Card>
    </div>
  )
}

function MicIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3Z" />
      <path d="M19 10v2a7 7 0 0 1-14 0v-2" />
      <line x1="12" x2="12" y1="19" y2="22" />
    </svg>
  )
}
