/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/NiOkR5WTqrI
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Cormorant_Garamond } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"

export function TermsAndPolicy() {
  return (
    <>
      <header className="fixed top-0 left-0 right-0 z-50 bg-white shadow-sm dark:bg-gray-950">
        <div className="container flex h-16 items-center justify-between px-4 md:px-6">
          <Link className="flex items-center" href="#">
            <MountainIcon className="h-6 w-6 text-[#6b5b95]" />
            <span className="ml-2 text-lg font-semibold text-[#6b5b95]">Acme App</span>
          </Link>
          <Button
            className="bg-[#6b5b95] text-white hover:bg-[#6b5b95]/90 focus-visible:ring-[#6b5b95]"
          >
            Get Started
          </Button>
        </div>
      </header>
      <main className="pt-20 pb-32">
        <section className="container px-4 md:px-6">
          <div className="mx-auto max-w-3xl space-y-8">
            <div>
              <h1 className="text-3xl font-bold text-[#6b5b95] sm:text-4xl md:text-5xl">
                Terms of Use and Privacy Policy
              </h1>
              <p className="mt-4 text-gray-500 dark:text-gray-400">
                Welcome to our app! By using our services, you agree to the following terms and conditions:
              </p>
            </div>
            <div className="space-y-4">
              <h2 className="text-xl font-bold text-[#6b5b95]">Terms of Use</h2>
              <p className="text-gray-500 dark:text-gray-400">
                1. You must be at least 13 years old to use our app.
                <br />
                2. You agree to use our app in a responsible and lawful manner.
                <br />
                3. We reserve the right to modify or terminate our services at any time.
              </p>
            </div>
            <div className="space-y-4">
              <h2 className="text-xl font-bold text-[#6b5b95]">Privacy Policy</h2>
              <p className="text-gray-500 dark:text-gray-400">
                1. We collect certain personal information to provide our services.
                <br />
                2. We will not share your information with third parties without your consent.
                <br />
                3. You have the right to access and delete your personal information.
              </p>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-[#6b5b95] text-white">
        <div className="container flex flex-col items-center justify-between gap-8 py-12 px-4 md:flex-row md:px-6">
          <div className="flex flex-col items-center gap-4 md:items-start">
            <Link className="flex items-center" href="#">
              <MountainIcon className="h-6 w-6" />
              <span className="ml-2 text-lg font-semibold">Acme App</span>
            </Link>
            <div className="flex gap-4">
              <Link className="text-sm hover:underline" href="#">
                Facebook
              </Link>
              <Link className="text-sm hover:underline" href="#">
                Twitter
              </Link>
              <Link className="text-sm hover:underline" href="#">
                Instagram
              </Link>
            </div>
          </div>
          <div className="flex flex-col items-center gap-4 md:items-start">
            <p className="text-sm">
              <MailIcon className="mr-2 inline-block h-4 w-4" />
              support@acmeapp.com
            </p>
            <p className="text-sm">
              <PhoneIcon className="mr-2 inline-block h-4 w-4" />
              +1 (555) 123-4567
            </p>
          </div>
          <div className="flex flex-col items-center gap-4 md:items-start">
            <Link className="text-sm hover:underline" href="#">
              Terms of Use
            </Link>
            <Link className="text-sm hover:underline" href="#">
              Privacy Policy
            </Link>
          </div>
        </div>
      </footer>
    </>
  )
}

function MailIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  )
}


function MountainIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function PhoneIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
    </svg>
  )
}
