/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/aoEjfuS0GGW
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from 'next/link'
import { Button } from "@/components/ui/button"
import { TooltipTrigger, TooltipContent, Tooltip, TooltipProvider } from "@/components/ui/tooltip"
import { DialogTrigger, DialogTitle, DialogDescription, DialogHeader, DialogFooter, DialogContent, Dialog } from "@/components/ui/dialog"
import { MessageCircleIcon, WhatsAppIcon } from "@/components/icons"

export function SupportDialog() {
  return (
    <div className="relative">
      <div className="fixed bottom-6 right-6">
        <TooltipProvider>
          <Tooltip>
            <TooltipTrigger asChild>
              <Button
                className="bg-gray-900 text-white hover:bg-gray-800 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-200"
                size="icon"
                variant="ghost"
              >
                <MessageCircleIcon className="h-6 w-6" />
                <span className="sr-only">Mais informações</span>
              </Button>
            </TooltipTrigger>
            <TooltipContent>Mais informações</TooltipContent>
          </Tooltip>
        </TooltipProvider>
      </div>
      <Dialog>
        <DialogTrigger asChild>
          <Button
            className="fixed bottom-6 right-6 bg-darkColor text-white hover:bg-mainColor dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-200"
            size="icon"
            variant="ghost"
          >
            <MessageCircleIcon className="h-6 w-6" />
            <span className="sr-only">Mais informações</span>
          </Button>
        </DialogTrigger>
        <DialogContent className="sm:max-w-[425px]">
          <DialogHeader>
            <DialogTitle>Alguma Dúvida?</DialogTitle>
            <DialogDescription>Envie-nos uma mensagem e nosso time te ajudará prontamente.</DialogDescription>
          </DialogHeader>
          <div className="grid gap-4 py-4">
            {/* <div className="grid items-center grid-cols-[auto_1fr] gap-4">
              <UserIcon className="h-6 w-6 text-gray-500 dark:text-gray-400" />
              <div>
                <div className="font-medium">Email</div>
                <div className="text-gray-500 dark:text-gray-400">support@example.com</div>
              </div>
            </div> */}
            
            {/* <div className="grid items-center grid-cols-[auto_1fr] gap-4">
              <PhoneIcon className="h-6 w-6 text-gray-500 dark:text-gray-400" />
              <div>
                <div className="font-medium">+55 (11) 123-4567</div>
                <div className="text-gray-500 dark:text-gray-400">Monday - Friday, 9am - 5pm</div>
              </div>
            </div> */}
            <div className="grid items-center grid-cols-[auto_1fr] gap-4">
              <div>
              <div className="font-medium">Mais informações</div>
              <div>
                <Link
                  className="bg-[#128c7e] text-white inline-flex items-center rounded-md bg-gray-900 px-4 py-2 text-sm font-medium shadow transition-colors hover:bg-[#075e54] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-darkColor dark:focus-visible:ring-gray-300"
                  href="https://api.whatsapp.com/send?phone=5511975966675&text=Ol%C3%A1!%20Eu%20gostaria%20de%20mais%20informa%C3%A7%C3%B5es%20sobre%20o%20Everylang%20para%20professores."
                >
                  <WhatsAppIcon className="mr-2 h-4 w-4" />
                Enviar mensagem
              </Link>
                
              </div>
              </div>
            </div>
          </div>
          {/* <DialogFooter>
            <Button type="button">Close</Button>
          </DialogFooter> */}
        </DialogContent>
      </Dialog>
    </div>
  )
}

